// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: property/property.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PropertyClient is the client API for Property service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropertyClient interface {
	GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error)
	AddAsset(ctx context.Context, in *AddAssetRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	ModifyAsset(ctx context.Context, in *ModifyAssetRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	DisableAsset(ctx context.Context, in *DisableAssetRequest, opts ...grpc.CallOption) (*ResultResponse, error)
	AddProperty(ctx context.Context, in *NewProperty, opts ...grpc.CallOption) (*ResultResponse, error)
}

type propertyClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyClient(cc grpc.ClientConnInterface) PropertyClient {
	return &propertyClient{cc}
}

func (c *propertyClient) GetAssets(ctx context.Context, in *GetAssetsRequest, opts ...grpc.CallOption) (*GetAssetsResponse, error) {
	out := new(GetAssetsResponse)
	err := c.cc.Invoke(ctx, "/Property/GetAssets", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyClient) AddAsset(ctx context.Context, in *AddAssetRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/Property/AddAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyClient) ModifyAsset(ctx context.Context, in *ModifyAssetRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/Property/ModifyAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyClient) DisableAsset(ctx context.Context, in *DisableAssetRequest, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/Property/DisableAsset", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *propertyClient) AddProperty(ctx context.Context, in *NewProperty, opts ...grpc.CallOption) (*ResultResponse, error) {
	out := new(ResultResponse)
	err := c.cc.Invoke(ctx, "/Property/AddProperty", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PropertyServer is the server API for Property service.
// All implementations must embed UnimplementedPropertyServer
// for forward compatibility
type PropertyServer interface {
	GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error)
	AddAsset(context.Context, *AddAssetRequest) (*ResultResponse, error)
	ModifyAsset(context.Context, *ModifyAssetRequest) (*ResultResponse, error)
	DisableAsset(context.Context, *DisableAssetRequest) (*ResultResponse, error)
	AddProperty(context.Context, *NewProperty) (*ResultResponse, error)
	mustEmbedUnimplementedPropertyServer()
}

// UnimplementedPropertyServer must be embedded to have forward compatible implementations.
type UnimplementedPropertyServer struct {
}

func (UnimplementedPropertyServer) GetAssets(context.Context, *GetAssetsRequest) (*GetAssetsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAssets not implemented")
}
func (UnimplementedPropertyServer) AddAsset(context.Context, *AddAssetRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddAsset not implemented")
}
func (UnimplementedPropertyServer) ModifyAsset(context.Context, *ModifyAssetRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ModifyAsset not implemented")
}
func (UnimplementedPropertyServer) DisableAsset(context.Context, *DisableAssetRequest) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableAsset not implemented")
}
func (UnimplementedPropertyServer) AddProperty(context.Context, *NewProperty) (*ResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddProperty not implemented")
}
func (UnimplementedPropertyServer) mustEmbedUnimplementedPropertyServer() {}

// UnsafePropertyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyServer will
// result in compilation errors.
type UnsafePropertyServer interface {
	mustEmbedUnimplementedPropertyServer()
}

func RegisterPropertyServer(s grpc.ServiceRegistrar, srv PropertyServer) {
	s.RegisterService(&Property_ServiceDesc, srv)
}

func _Property_GetAssets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAssetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).GetAssets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Property/GetAssets",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).GetAssets(ctx, req.(*GetAssetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Property_AddAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).AddAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Property/AddAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).AddAsset(ctx, req.(*AddAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Property_ModifyAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ModifyAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).ModifyAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Property/ModifyAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).ModifyAsset(ctx, req.(*ModifyAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Property_DisableAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).DisableAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Property/DisableAsset",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).DisableAsset(ctx, req.(*DisableAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Property_AddProperty_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewProperty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PropertyServer).AddProperty(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Property/AddProperty",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PropertyServer).AddProperty(ctx, req.(*NewProperty))
	}
	return interceptor(ctx, in, info, handler)
}

// Property_ServiceDesc is the grpc.ServiceDesc for Property service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Property_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Property",
	HandlerType: (*PropertyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAssets",
			Handler:    _Property_GetAssets_Handler,
		},
		{
			MethodName: "AddAsset",
			Handler:    _Property_AddAsset_Handler,
		},
		{
			MethodName: "ModifyAsset",
			Handler:    _Property_ModifyAsset_Handler,
		},
		{
			MethodName: "DisableAsset",
			Handler:    _Property_DisableAsset_Handler,
		},
		{
			MethodName: "AddProperty",
			Handler:    _Property_AddProperty_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "property/property.proto",
}
