// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: property-listing/property-listing.proto

package proto

import (
	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PropertyListingClient is the client API for PropertyListing service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PropertyListingClient interface {
}

type propertyListingClient struct {
	cc grpc.ClientConnInterface
}

func NewPropertyListingClient(cc grpc.ClientConnInterface) PropertyListingClient {
	return &propertyListingClient{cc}
}

// PropertyListingServer is the server API for PropertyListing service.
// All implementations must embed UnimplementedPropertyListingServer
// for forward compatibility
type PropertyListingServer interface {
	mustEmbedUnimplementedPropertyListingServer()
}

// UnimplementedPropertyListingServer must be embedded to have forward compatible implementations.
type UnimplementedPropertyListingServer struct {
}

func (UnimplementedPropertyListingServer) mustEmbedUnimplementedPropertyListingServer() {}

// UnsafePropertyListingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PropertyListingServer will
// result in compilation errors.
type UnsafePropertyListingServer interface {
	mustEmbedUnimplementedPropertyListingServer()
}

func RegisterPropertyListingServer(s grpc.ServiceRegistrar, srv PropertyListingServer) {
	s.RegisterService(&PropertyListing_ServiceDesc, srv)
}

// PropertyListing_ServiceDesc is the grpc.ServiceDesc for PropertyListing service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PropertyListing_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "PropertyListing",
	HandlerType: (*PropertyListingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams:     []grpc.StreamDesc{},
	Metadata:    "property-listing/property-listing.proto",
}
